#!/usr/bin/env python3
"""
StateLink — Auto-Start Setup
=============================
One-click setup to make the StateLink monitor server start automatically
when you log into your computer. No more manually double-clicking!

Supports: Windows 10/11  and  macOS 12+

HOW TO USE:
    python setup_autostart.py

    Or on Windows, double-click this file after Python is installed.
    On Mac, right-click → Open With → Python Launcher.

The script will:
  1. Detect your operating system
  2. Find the statelink_server.py location
  3. Set up auto-start (Startup folder on Windows, LaunchAgent on Mac)
  4. NOT start the server right now — it will start on next login

To REMOVE auto-start, run:
    python setup_autostart.py --remove
"""

import os
import sys
import shutil
import platform
import subprocess
import tempfile

# ─────────────────────────────────────────────────────────
#  Path helpers
# ─────────────────────────────────────────────────────────

def get_server_dir():
    """Get the directory containing this script and statelink_server.py."""
    return os.path.dirname(os.path.abspath(__file__))


def get_server_script():
    """Full path to statelink_server.py."""
    return os.path.join(get_server_dir(), "statelink_server.py")


def find_python():
    """Find the python executable. Returns path or None."""
    # Try python3 first (macOS), then python (Windows)
    for name in ["python3", "python"]:
        try:
            result = subprocess.run(
                [name, "--version"],
                capture_output=True, text=True, timeout=5
            )
            if result.returncode == 0:
                return name
        except (FileNotFoundError, subprocess.TimeoutExpired):
            continue

    # Try full paths on Windows
    if platform.system() == "Windows":
        for py_ver in ["312", "311", "310", "39", "38"]:
            for base in [
                os.path.expandvars(r"%LOCALAPPDATA%\Programs\Python\Python" + py_ver),
                os.path.expandvars(r"%PROGRAMFILES%\Python" + py_ver),
                r"C:\Python" + py_ver,
            ]:
                candidate = os.path.join(base, "python.exe")
                if os.path.isfile(candidate):
                    return candidate

    return None


# ─────────────────────────────────────────────────────────
#  Windows: Startup folder
# ─────────────────────────────────────────────────────────

def windows_setup():
    """Set up auto-start on Windows using the Startup folder."""
    print()
    print("  Platform: Windows")
    print()

    server_dir = get_server_dir()
    vbs_template = os.path.join(server_dir, "start_server_win.vbs")
    server_script = get_server_script()
    python_exe = find_python()

    if not python_exe:
        print("  ERROR: Python not found.")
        print("  Please install Python from https://python.org first.")
        return False

    print(f"  Python:  {python_exe}")
    print(f"  Server:  {server_script}")
    print()

    # ── Determine the pythonw path (no console window) ──
    pythonw = python_exe.replace("python.exe", "pythonw.exe") if python_exe.endswith(".exe") else python_exe
    if platform.system() == "Windows" and not pythonw.endswith("pythonw.exe"):
        pythonw_dir = os.path.dirname(python_exe)
        candidate = os.path.join(pythonw_dir, "pythonw.exe")
        if os.path.isfile(candidate):
            pythonw = candidate
        else:
            # Fallback: use python.exe (will show a brief console)
            pythonw = python_exe
            print("  Note: pythonw.exe not found; a brief console may appear.")

    # ── Write the VBS file with correct paths ──
    # VBS requires doubled double-quotes to escape them:
    #   WshShell.Run """C:\pythonw.exe"" ""C:\server.py""", 0, False
    # This appears as: WshShell.Run "C:\pythonw.exe" "C:\server.py", 0, False
    vbs_run_args = '"""' + pythonw + '"" """' + server_script + '"""'

    vbs_content = (
        "' StateLink auto-start launcher (generated by setup_autostart.py)\n"
        'Set WshShell = CreateObject("WScript.Shell")\n'
        'WshShell.CurrentDirectory = "' + server_dir + '"\n'
        'WshShell.Run ' + vbs_run_args + ', 0, False\n'
        'Set WshShell = Nothing\n'
    )

    vbs_path = os.path.join(server_dir, "statelink_autostart.vbs")
    with open(vbs_path, "w") as f:
        f.write(vbs_content)
    print(f"  Created:  {vbs_path}")

    # ── Create shortcut in Startup folder ──
    startup_folder = os.path.expandvars(
        r"%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup"
    )

    # We'll create a .bat file that references the VBS, since creating
    # an actual .lnk shortcut requires win32com or PowerShell.
    bat_path = os.path.join(startup_folder, "StateLink Monitor.bat")
    bat_content = f'''@echo off
rem StateLink Monitor — auto-start
cd /d "{server_dir}"
cscript //nologo "{vbs_path}"
'''

    try:
        os.makedirs(startup_folder, exist_ok=True)
        with open(bat_path, "w") as f:
            f.write(bat_content)
        print(f"  Startup:  {bat_path}")
    except Exception as e:
        print(f"  WARNING: Could not write to Startup folder: {e}")
        print()
        print("  Manual setup:")
        print(f"  1. Press Win+R, type: shell:startup")
        print(f"  2. Create a shortcut to: {vbs_path}")
        return False

    print()
    print("  ========================================")
    print("  Auto-start is now ENABLED!")
    print()
    print("  The StateLink server will start")
    print("  automatically next time you log in.")
    print("  ========================================")
    return True


def windows_remove():
    """Remove auto-start on Windows."""
    startup_folder = os.path.expandvars(
        r"%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup"
    )
    bat_path = os.path.join(startup_folder, "StateLink Monitor.bat")
    vbs_path = os.path.join(get_server_dir(), "statelink_autostart.vbs")

    removed = False
    for p in [bat_path, vbs_path]:
        if os.path.isfile(p):
            os.remove(p)
            print(f"  Removed: {p}")
            removed = True

    if removed:
        print()
        print("  Auto-start has been DISABLED.")
    else:
        print("  Auto-start was not enabled (nothing to remove).")
    return True


# ─────────────────────────────────────────────────────────
#  macOS: LaunchAgent
# ─────────────────────────────────────────────────────────

def macos_setup():
    """Set up auto-start on macOS using a LaunchAgent."""
    print()
    print("  Platform: macOS")
    print()

    server_dir = get_server_dir()
    server_script = get_server_script()
    python_exe = find_python()

    if not python_exe:
        print("  ERROR: Python not found.")
        return False

    # Resolve full path of python
    python_path = python_exe
    if python_exe == "python3":
        try:
            result = subprocess.run(
                ["which", "python3"],
                capture_output=True, text=True, timeout=5
            )
            if result.returncode == 0:
                python_path = result.stdout.strip()
        except Exception:
            pass

    print(f"  Python:  {python_path}")
    print(f"  Server:  {server_script}")
    print()

    # ── Generate plist ──
    plist_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.statelink.monitor</string>
    <key>ProgramArguments</key>
    <array>
        <string>{python_path}</string>
        <string>{server_script}</string>
    </array>
    <key>WorkingDirectory</key>
    <string>{server_dir}</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <false/>
    <key>StandardOutPath</key>
    <string>{server_dir}/statelink_server.log</string>
    <key>StandardErrorPath</key>
    <string>{server_dir}/statelink_server_error.log</string>
    <key>ProcessType</key>
    <string>Background</string>
</dict>
</plist>
"""

    # ── Write plist to LaunchAgents ──
    launch_agents_dir = os.path.expanduser("~/Library/LaunchAgents")
    os.makedirs(launch_agents_dir, exist_ok=True)

    plist_path = os.path.join(launch_agents_dir, "com.statelink.monitor.plist")
    with open(plist_path, "w") as f:
        f.write(plist_content)
    print(f"  Created:  {plist_path}")

    # ── Unload if already loaded, then load ──
    subprocess.run(
        ["launchctl", "unload", plist_path],
        capture_output=True, timeout=5
    )
    result = subprocess.run(
        ["launchctl", "load", plist_path],
        capture_output=True, text=True, timeout=5
    )

    if result.returncode != 0:
        print(f"  WARNING: launchctl load may have failed: {result.stderr}")
        print()
        print("  Don't worry — the agent will still load at next login.")
        print("  Or you can load it now manually:")
        print(f"    launchctl load {plist_path}")

    print()
    print("  ========================================")
    print("  Auto-start is now ENABLED!")
    print()
    print("  The StateLink server will start")
    print("  automatically next time you log in.")
    print()
    print("  To also start it RIGHT NOW:")
    print(f"    launchctl load {plist_path}")
    print("  ========================================")
    return True


def macos_remove():
    """Remove auto-start on macOS."""
    plist_path = os.path.expanduser(
        "~/Library/LaunchAgents/com.statelink.monitor.plist"
    )

    if os.path.isfile(plist_path):
        subprocess.run(
            ["launchctl", "unload", plist_path],
            capture_output=True, timeout=5
        )
        os.remove(plist_path)
        print(f"  Removed: {plist_path}")
        print()
        print("  Auto-start has been DISABLED.")
    else:
        print("  Auto-start was not enabled (nothing to remove).")

    # Also clean up log files
    server_dir = get_server_dir()
    for log_file in ["statelink_server.log", "statelink_server_error.log"]:
        log_path = os.path.join(server_dir, log_file)
        if os.path.isfile(log_path):
            try:
                os.remove(log_path)
            except Exception:
                pass

    return True


# ─────────────────────────────────────────────────────────
#  Pre-flight checks
# ─────────────────────────────────────────────────────────

def check_prerequisites():
    """Verify everything needed is in place."""
    server_script = get_server_script()

    issues = []

    if not os.path.isfile(server_script):
        issues.append(f"Server script not found: {server_script}")

    python = find_python()
    if not python:
        issues.append(
            "Python not found. Install from https://python.org"
        )
    else:
        # Check psutil
        try:
            subprocess.run(
                [python, "-c", "import psutil"],
                capture_output=True, timeout=10,
                check=True
            )
        except subprocess.CalledProcessError:
            issues.append(
                "Package 'psutil' is not installed.\n"
                f"  Run: {python} -m pip install psutil"
            )

    if issues:
        print()
        print("  ⚠  Issues found:")
        for i in issues:
            print(f"    - {i}")
        print()
        return False

    return True


# ─────────────────────────────────────────────────────────
#  Main
# ─────────────────────────────────────────────────────────

def print_banner():
    print()
    print("╔══════════════════════════════════════════╗")
    print("║   StateLink — Auto-Start Setup          ║")
    print("║   Launch server on login automatically  ║")
    print("╚══════════════════════════════════════════╝")


def main():
    print_banner()

    remove_mode = "--remove" in sys.argv or "--uninstall" in sys.argv

    # Check prerequisites (skip if removing)
    if not remove_mode:
        if not check_prerequisites():
            print("  Please fix the above issues and try again.")
            input("  Press Enter to exit...")
            sys.exit(1)

    # Detect OS and run appropriate setup
    system = platform.system()

    if system == "Windows":
        success = windows_remove() if remove_mode else windows_setup()
    elif system == "Darwin":
        success = macos_remove() if remove_mode else macos_setup()
    else:
        print(f"  Unsupported platform: {system}")
        print("  This tool supports Windows and macOS only.")
        sys.exit(1)

    if not remove_mode and success:
        print()
        print("  TIP: To disable auto-start later, run:")
        print("    python setup_autostart.py --remove")
        print()

    if sys.stdin.isatty():
        input("  Press Enter to exit...")


if __name__ == "__main__":
    main()
